name = "Cocoa-EH"
license = "MIT"
licenselink = "https://github.com/fuegowolf/cocoa-eh-hugo-theme/blob/master/LICENSE.md"
description = "Cocoa Enhanced is a clean, fast and responsive theme with cool typography."
homepage = "https://github.com/fuegowolf/cocoa-eh-hugo-theme"
tags = ["clean", "fast", "responsive", "typography"]
features = ["flexible", "fast", "highlights", "progressive images", "disqus"]
min_version = 0.20.2

[author]
    name = "Alexis Tacnet"
    homepage = "https://github.com/fuegowolf"

[original]
    name = "Nishanth Shanmugham"
    homepage = "https://github.com/nishanths"
    repo = "https://www.github.com/nishanths/cocoa-hugo-theme"
